eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
datasource:
  url: jdbc:postgresql://localhost:5432/vifrin
  username: postgres
  password: '09071999'
  driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect